### ISSUE TITLE
Writer implementation Command

### ISSUE THREAD

**Issue by tischi** [mobie/bigdataviewer-imageloader#23]
@K-Meech 

I think it would be great if we could add a very simple ImageJ Command to save the current ImagePlus as ome.zarr.

However, maybe we are rather adding this UI Command to the mobie-fiji-viewer repo as there also is the loader?

**Comment by K-Meech** [comment]
Sounds good! I can add this while I'm adding all the stuff for the project creator.
I think all the commands for opening ome-zarr have moved to this repo? e.g. https://github.com/mobie/bigdataviewer-imageloader/blob/d723edbc5985c5385e5f2d2ee60ca6becc2e768d/src/test/java/ui/OpenOMEZARRCommand.java I couldn't see them in mobie-fiji-viewer.

They're all in the /src/test/ for now. Did you want them in /src/main?

**Comment by KateMoreva** [comment]
> Sounds good! I can add this while I'm adding all the stuff for the project creator.
> I think all the commands for opening ome-zarr have moved to this repo? e.g. https://github.com/mobie/bigdataviewer-imageloader/blob/d723edbc5985c5385e5f2d2ee60ca6becc2e768d/src/test/java/ui/OpenOMEZARRCommand.java I couldn't see them in mobie-fiji-viewer.
> 
> They're all in the /src/test/ for now. Did you want them in /src/main?

I thought that the idea was to have Commands in MoBIE and everything needed for SpimData in `bigdataviewer-imageloader`
Maybe something went wrong while merging.
I'll fix it now.

**Comment by KateMoreva** [comment]
> Sounds good! I can add this while I'm adding all the stuff for the project creator.
> I think all the commands for opening ome-zarr have moved to this repo? e.g. https://github.com/mobie/bigdataviewer-imageloader/blob/d723edbc5985c5385e5f2d2ee60ca6becc2e768d/src/test/java/ui/OpenOMEZARRCommand.java I couldn't see them in mobie-fiji-viewer.
> 
> They're all in the /src/test/ for now. Did you want them in /src/main?

@K-Meech, place use this version of MoBIE, commands are once again there  
https://github.com/mobie/mobie-viewer-fiji/pull/419

**Comment by K-Meech** [comment]
Great - thanks @KateMoreva! I'll add the writer command to the MoBIE repo

**Comment by K-Meech** [comment]
This is on the develop branch now
