### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by tischi** [mobie/bigdataviewer-imageloader#24]
@KateMoreva The current master does a lot of logging:

```
Preparing image /s3 of data type float32
/s3 [0, 0] ...
/s3 [0, 0] fetched 14976 voxels in 75 ms.
Preparing image /s3 of data type float32
/s3 [0, 0] ...
/s3 [0, 0] fetched 14976 voxels in 91 ms.
Preparing image /s3 of data type float32
/s3 [0, 0] ...
/s3 [0, 0] fetched 14976 voxels in 88 ms.
Preparing image /s3 of data type float32
/s3 [0, 0] ...
/s3 [0, 0] fetched 14976 voxels in 88 ms.
/s3 [0, 0] fetched 14976 voxels in 69 ms.
```

Should we disable this or do you still need it for the debugging?

**Comment by KateMoreva** [comment]
I do not need it for debugging.

**Comment by KateMoreva** [comment]
I'll make the needed changes in master today.

**Comment by KateMoreva** [comment]
The logging is turned off in the `master` but, you need to have the correct files from `bigdataviewer-imageloader`. I suggest finding the sources in the `maven` folder on your machine and clear them before `reloading` dependencies.

**Comment by tischi** [comment]
Thanks a lot!
My workflow was: 

1. pull the latest master of bdv-imgloader (i.e. 1.0.2-SNAPSHOT)
2. mvn clean install bdv-imgloader
3. switch to mobie-fiji-viewer 
4. aaah, and then I probably forgot to `mvn -> reload project` (normally I do this)....I guess otherwise it should have worked?

**Comment by KateMoreva** [comment]
Sometimes it is needed to be cleaned in the folder _by hands_ in the folder (something like /home/katerina/.m2/repository/mobie/bigdataviewer-imageloader/1.0.2-SNAPSHOT).

**Comment by KateMoreva** [comment]
> Thanks a lot!
> My workflow was:
> 
> 1. pull the latest master of bdv-imgloader (i.e. 1.0.2-SNAPSHOT)
> 2. mvn clean install bdv-imgloader
> 3. switch to mobie-fiji-viewer
> 4. aaah, and then I probably forgot to `mvn -> reload project` (normally I do this)....I guess otherwise it should have worked?

Nise workflow, but you actually can make it a bit easier (just leave 3, 4 points and clean the folder with the version from time to time). I am trying to not allow situations when the source files (for the current in-use version) are changing.
