### ISSUE TITLE
Test dependency

### ISSUE THREAD

**Issue by tischi** [mobie/bigdataviewer-imageloader#25]
@KateMoreva I am curious, what is this dependency about:

```
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.5.2</version>
            <scope>test</scope>
        </dependency>
```

What's the difference to simply this one?

```
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
		</dependency>
```

**Comment by KateMoreva** [comment]
The upper dependency is for JUnit5, the second one should be for JUnit4.

**Comment by tischi** [comment]
OK! So you are essentially using the more modern one? I guess I should also switch?

**Comment by KateMoreva** [comment]
It depends on your tests. If you want to use Before/AfterEach, Before/AfterAll methods and several other features surely:)
